// Code generated by MockGen. DO NOT EDIT.
// Source: deleteme/webhook (interfaces: ProjectSource,ProjectHookClient)
//
// Generated by this command:
//
//	mockgen -destination webhook/registrar_mocks_test.go -package webhook deleteme/webhook ProjectSource,ProjectHookClient
//

// Package webhook is a generated GoMock package.
package webhook

import (
	context "context"
	reflect "reflect"

	gitlab "gitlab.com/gitlab-org/api/client-go"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectSource is a mock of ProjectSource interface.
type MockProjectSource struct {
	ctrl     *gomock.Controller
	recorder *MockProjectSourceMockRecorder
	isgomock struct{}
}

// MockProjectSourceMockRecorder is the mock recorder for MockProjectSource.
type MockProjectSourceMockRecorder struct {
	mock *MockProjectSource
}

// NewMockProjectSource creates a new mock instance.
func NewMockProjectSource(ctrl *gomock.Controller) *MockProjectSource {
	mock := &MockProjectSource{ctrl: ctrl}
	mock.recorder = &MockProjectSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectSource) EXPECT() *MockProjectSourceMockRecorder {
	return m.recorder
}

// ListProjectIDs mocks base method.
func (m *MockProjectSource) ListProjectIDs(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectIDs", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectIDs indicates an expected call of ListProjectIDs.
func (mr *MockProjectSourceMockRecorder) ListProjectIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectIDs", reflect.TypeOf((*MockProjectSource)(nil).ListProjectIDs), ctx)
}

// MockProjectHookClient is a mock of ProjectHookClient interface.
type MockProjectHookClient struct {
	ctrl     *gomock.Controller
	recorder *MockProjectHookClientMockRecorder
	isgomock struct{}
}

// MockProjectHookClientMockRecorder is the mock recorder for MockProjectHookClient.
type MockProjectHookClientMockRecorder struct {
	mock *MockProjectHookClient
}

// NewMockProjectHookClient creates a new mock instance.
func NewMockProjectHookClient(ctrl *gomock.Controller) *MockProjectHookClient {
	mock := &MockProjectHookClient{ctrl: ctrl}
	mock.recorder = &MockProjectHookClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectHookClient) EXPECT() *MockProjectHookClientMockRecorder {
	return m.recorder
}

// AddProjectHook mocks base method.
func (m *MockProjectHookClient) AddProjectHook(ctx context.Context, projectID int64, opt *gitlab.AddProjectHookOptions) (*gitlab.ProjectHook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProjectHook", ctx, projectID, opt)
	ret0, _ := ret[0].(*gitlab.ProjectHook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProjectHook indicates an expected call of AddProjectHook.
func (mr *MockProjectHookClientMockRecorder) AddProjectHook(ctx, projectID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProjectHook", reflect.TypeOf((*MockProjectHookClient)(nil).AddProjectHook), ctx, projectID, opt)
}

// EditProjectHook mocks base method.
func (m *MockProjectHookClient) EditProjectHook(ctx context.Context, projectID, hookID int64, opt *gitlab.EditProjectHookOptions) (*gitlab.ProjectHook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditProjectHook", ctx, projectID, hookID, opt)
	ret0, _ := ret[0].(*gitlab.ProjectHook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditProjectHook indicates an expected call of EditProjectHook.
func (mr *MockProjectHookClientMockRecorder) EditProjectHook(ctx, projectID, hookID, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditProjectHook", reflect.TypeOf((*MockProjectHookClient)(nil).EditProjectHook), ctx, projectID, hookID, opt)
}

// ListProjectHooks mocks base method.
func (m *MockProjectHookClient) ListProjectHooks(ctx context.Context, projectID int64) ([]*gitlab.ProjectHook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectHooks", ctx, projectID)
	ret0, _ := ret[0].([]*gitlab.ProjectHook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectHooks indicates an expected call of ListProjectHooks.
func (mr *MockProjectHookClientMockRecorder) ListProjectHooks(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectHooks", reflect.TypeOf((*MockProjectHookClient)(nil).ListProjectHooks), ctx, projectID)
}
